=== Bernardo-MG/Tabletop-Punkapocalyptic-Punkabuilder/src/main/resources/model/validation/punkapocalyptic-model-psychic-power.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="psychic_powers">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="psychic_power" type="psychic" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="psychic_power" />
			<xs:field xpath="name" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="psychic">
		<xs:sequence>
			<xs:element name="name" type="xs:token" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Punkapocalyptic-Punkabuilder/src/main/resources/model/punkapocalyptic-model-psychic-powers.xml
<?xml version="1.0" encoding="UTF-8"?>
<psychic_powers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="validation/punkapocalyptic-model-psychic-power.xsd">
	<psychic_power>
		<name>disarm</name>
	</psychic_power>
	<psychic_power>
		<name>enhancement</name>
	</psychic_power>
	<psychic_power>
		<name>master_of_puppets</name>
	</psychic_power>
	<psychic_power>
		<name>mindshock</name>
	</psychic_power>
	<psychic_power>
		<name>psychic_barrier</name>
	</psychic_power>
</psychic_powers>
