=== Bernardo-MG/Tabletop-Punkapocalyptic-Punkabuilder/src/main/resources/model/validation/punkapocalyptic-model-armor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="armor_profiles">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="armor_profile" type="armor" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="armor_profile" />
			<xs:field xpath="name" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="armor">
		<xs:sequence>
			<xs:element name="name" type="xs:token" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="rules" type="rulesList" maxOccurs="1"
				minOccurs="0">
				<xs:unique name="uniqueRule">
					<xs:selector xpath="rule" />
					<xs:field xpath="." />
				</xs:unique>
			</xs:element>
			<xs:element name="protection" type="xs:int" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="rulesList">
		<xs:sequence>
			<xs:element name="rule" type="xs:token" maxOccurs="unbounded"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Punkapocalyptic-Punkabuilder/src/main/resources/model/punkapocalyptic-model-armor.xml
<?xml version="1.0" encoding="UTF-8"?>
<armor_profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="validation/punkapocalyptic-model-armor.xsd">
	<armor_profile>
		<name>bulletproof_vest</name>
		<protection>3</protection>
	</armor_profile>
	<armor_profile>
		<name>hardened_leather</name>
		<protection>2</protection>
	</armor_profile>
	<armor_profile>
		<name>metal_plate</name>
		<rules>
			<rule>cumbersome</rule>
		</rules>
		<protection>5</protection>
	</armor_profile>
	<armor_profile>
		<name>metallic_armor</name>
		<protection>4</protection>
	</armor_profile>
	<armor_profile>
		<name>thick_clothes</name>
		<protection>1</protection>
	</armor_profile>
	<armor_profile>
		<name>unarmored</name>
		<protection>0</protection>
	</armor_profile>
</armor_profiles>
