=== Bernardo-MG/Tabletop-Punkapocalyptic-Punkabuilder/src/main/resources/model/validation/punkapocalyptic-model-unit-mutation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="unit_mutations">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="unit_mutation" type="mutation" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="unit" />
			<xs:field xpath="." />
		</xs:unique>
	</xs:element>

	<xs:complexType name="mutation">
		<xs:sequence>
			<xs:element name="unit" type="xs:token" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="max_mutations" type="xs:int" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="white_list" type="mutationList"
				maxOccurs="1" minOccurs="0" />
			<xs:element name="initial" type="mutationList"
				maxOccurs="1" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="mutationList">
		<xs:sequence>
			<xs:element name="mutation" type="xs:token" maxOccurs="unbounded"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Punkapocalyptic-Punkabuilder/src/main/resources/model/punkapocalyptic-model-unit-mutation.xml
<?xml version="1.0" encoding="UTF-8"?>
<unit_mutations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="validation/punkapocalyptic-model-unit-mutation.xsd">
	<unit_mutation>
		<unit>mutard</unit>
		<max_mutations>3</max_mutations>
	</unit_mutation>
	<unit_mutation>
		<unit>pit_beast</unit>
		<max_mutations>1</max_mutations>
		<white_list>
			<mutation>acid_spit</mutation>
			<mutation>brutal_charge</mutation>
			<mutation>extra_limbs</mutation>
			<mutation>poisoned_claws</mutation>
			<mutation>sure_feet</mutation>
			<mutation>thorns</mutation>
		</white_list>
		<initial>
			<mutation>hunk</mutation>
			<mutation>resilient</mutation>
			<mutation>tough_skin_2</mutation>
		</initial>
	</unit_mutation>
</unit_mutations>
