=== Bernardo-MG/Tabletop-Punkapocalyptic-Punkabuilder/src/main/resources/model/validation/punkapocalyptic-model-mutation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="mutations">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="mutation" type="mutation" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="mutation" />
			<xs:field xpath="name" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="mutation">
		<xs:sequence>
			<xs:element name="name" type="xs:token" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="bonus" type="bonusList" maxOccurs="1"
				minOccurs="0" />
			<xs:element name="cost" type="xs:int" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="bonusList">
		<xs:sequence>
			<xs:element name="actions" type="xs:integer" maxOccurs="1"
				minOccurs="0" />
			<xs:element name="agility" type="xs:integer" maxOccurs="1"
				minOccurs="0" />
			<xs:element name="combat" type="xs:integer" maxOccurs="1"
				minOccurs="0" />
			<xs:element name="precision" type="xs:integer" maxOccurs="1"
				minOccurs="0" />
			<xs:element name="strength" type="xs:integer" maxOccurs="1"
				minOccurs="0" />
			<xs:element name="tech" type="xs:integer" maxOccurs="1"
				minOccurs="0" />
			<xs:element name="toughness" type="xs:integer" maxOccurs="1"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Punkapocalyptic-Punkabuilder/src/main/resources/model/punkapocalyptic-model-mutation.xml
<?xml version="1.0" encoding="UTF-8"?>
<mutations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="validation/punkapocalyptic-model-mutation.xsd">
	<mutation>
		<name>able</name>
		<bonus>
			<actions>1</actions>
		</bonus>
		<cost>20</cost>
	</mutation>
	<mutation>
		<name>acid_spit</name>
		<cost>5</cost>
	</mutation>
	<mutation>
		<name>brutal_charge</name>
		<cost>6</cost>
	</mutation>
	<mutation>
		<name>claws</name>
		<cost>2</cost>
	</mutation>
	<mutation>
		<name>extra_limbs</name>
		<bonus>
			<combat>2</combat>
		</bonus>
		<cost>10</cost>
	</mutation>
	<mutation>
		<name>frog</name>
		<cost>6</cost>
	</mutation>
	<mutation>
		<name>hunk</name>
		<bonus>
			<strength>2</strength>
		</bonus>
		<cost>10</cost>
	</mutation>
	<mutation>
		<name>mimetism</name>
		<cost>6</cost>
	</mutation>
	<mutation>
		<name>organic_missile</name>
		<cost>10</cost>
	</mutation>
	<mutation>
		<name>poisoned_claws</name>
		<cost>8</cost>
	</mutation>
	<mutation>
		<name>prehensile_limb</name>
		<cost>5</cost>
	</mutation>
	<mutation>
		<name>psychic_echo</name>
		<cost>20</cost>
	</mutation>
	<mutation>
		<name>resilient</name>
		<bonus>
			<toughness>2</toughness>
		</bonus>
		<cost>10</cost>
	</mutation>
	<mutation>
		<name>runner</name>
		<cost>10</cost>
	</mutation>
	<mutation>
		<name>sharp_senses</name>
		<bonus>
			<agility>2</agility>
		</bonus>
		<cost>8</cost>
	</mutation>
	<mutation>
		<name>sharp_tail</name>
		<cost>10</cost>
	</mutation>
	<mutation>
		<name>sonar</name>
		<cost>5</cost>
	</mutation>
	<mutation>
		<name>sticky</name>
		<cost>10</cost>
	</mutation>
	<mutation>
		<name>sure_feet</name>
		<cost>6</cost>
	</mutation>
	<mutation>
		<name>thorns</name>
		<cost>6</cost>
	</mutation>
	<mutation>
		<name>tough_skin_1</name>
		<cost>5</cost>
	</mutation>
	<mutation>
		<name>tough_skin_3</name>
		<cost>10</cost>
	</mutation>
	<mutation>
		<name>tough_skin_5</name>
		<cost>20</cost>
	</mutation>
</mutations>
