=== Bernardo-MG/Tabletop-Punkapocalyptic-Punkabuilder/src/main/resources/model/validation/punkapocalyptic-model-unit-profile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="unit_profiles">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="unit_profile" type="profile" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="unit" />
			<xs:field xpath="name" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="profile">
		<xs:sequence>
			<xs:element name="name" type="xs:token" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="actions" type="xs:integer" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="combat" type="xs:integer" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="precision" type="xs:integer" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="agility" type="xs:integer" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="strength" type="xs:integer" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="toughness" type="xs:integer" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="tech" type="xs:integer" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="cost" type="xs:integer" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="rules" type="unit_rules" maxOccurs="1"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="unit_rules">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="rule" type="xs:token" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Punkapocalyptic-Punkabuilder/src/main/resources/model/punkapocalyptic-model-unit-profile.xml
<?xml version="1.0" encoding="UTF-8"?>
<unit_profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="validation/punkapocalyptic-model-unit-profile.xsd">
	<unit_profile>
		<name>addler</name>
		<actions>1</actions>
		<combat>1</combat>
		<precision>0</precision>
		<agility>1</agility>
		<strength>2</strength>
		<toughness>2</toughness>
		<tech>0</tech>
		<cost>6</cost>
		<rules>
			<rule>pack</rule>
			<rule>mong</rule>
		</rules>
	</unit_profile>
	<unit_profile>
		<name>bobblehead</name>
		<actions>3</actions>
		<combat>1</combat>
		<precision>3</precision>
		<agility>2</agility>
		<strength>2</strength>
		<toughness>2</toughness>
		<tech>7</tech>
		<cost>80</cost>
	</unit_profile>
	<unit_profile>
		<name>chief</name>
		<actions>3</actions>
		<combat>6</combat>
		<precision>6</precision>
		<agility>6</agility>
		<strength>4</strength>
		<toughness>4</toughness>
		<tech>5</tech>
		<cost>70</cost>
	</unit_profile>
	<unit_profile>
		<name>badass</name>
		<actions>2</actions>
		<combat>6</combat>
		<precision>6</precision>
		<agility>5</agility>
		<strength>4</strength>
		<toughness>4</toughness>
		<tech>4</tech>
		<cost>40</cost>
	</unit_profile>
	<unit_profile>
		<name>brute</name>
		<actions>2</actions>
		<combat>5</combat>
		<precision>4</precision>
		<agility>4</agility>
		<strength>5</strength>
		<toughness>4</toughness>
		<tech>2</tech>
		<cost>40</cost>
	</unit_profile>
	<unit_profile>
		<name>ganger</name>
		<actions>2</actions>
		<combat>5</combat>
		<precision>5</precision>
		<agility>5</agility>
		<strength>4</strength>
		<toughness>3</toughness>
		<tech>3</tech>
		<cost>30</cost>
	</unit_profile>
	<unit_profile>
		<name>mongrelmorph</name>
		<actions>2</actions>
		<combat>4</combat>
		<precision>0</precision>
		<agility>7</agility>
		<strength>4</strength>
		<toughness>3</toughness>
		<tech>0</tech>
		<cost>16</cost>
		<rules>
			<rule>beast</rule>
			<rule>swift</rule>
		</rules>
	</unit_profile>
	<unit_profile>
		<name>mutard</name>
		<actions>2</actions>
		<combat>3</combat>
		<precision>3</precision>
		<agility>3</agility>
		<strength>3</strength>
		<toughness>3</toughness>
		<tech>3</tech>
		<cost>12</cost>
	</unit_profile>
	<unit_profile>
		<name>pit_beast</name>
		<actions>2</actions>
		<combat>4</combat>
		<precision>2</precision>
		<agility>2</agility>
		<strength>6</strength>
		<toughness>6</toughness>
		<tech>1</tech>
		<cost>70</cost>
		<rules>
			<rule>berserk</rule>
		</rules>
	</unit_profile>
	<unit_profile>
		<name>scumbag</name>
		<actions>2</actions>
		<combat>4</combat>
		<precision>4</precision>
		<agility>4</agility>
		<strength>4</strength>
		<toughness>3</toughness>
		<tech>3</tech>
		<cost>20</cost>
	</unit_profile>
</unit_profiles>
