=== Bernardo-MG/Tabletop-Punkapocalyptic-Punkabuilder/src/main/resources/model/validation/punkapocalyptic-model-unit-armor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="unit_armors">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="unit_armor" type="availability" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="unit" />
			<xs:field xpath="." />
		</xs:unique>
	</xs:element>

	<xs:complexType name="availability">
		<xs:sequence>
			<xs:element name="unit" type="xs:token" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="armor" type="xs:token" maxOccurs="1"
				minOccurs="0" />
			<xs:element name="armors" type="armorList" maxOccurs="1"
				minOccurs="0">
				<xs:unique name="uniqueArmor">
					<xs:selector xpath="armor" />
					<xs:field xpath="name" />
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="armorList">
		<xs:sequence>
			<xs:element name="armor" type="armorData" maxOccurs="unbounded"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="armorData">
		<xs:sequence>
			<xs:element name="name" type="xs:token" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="cost" type="xs:integer" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Punkapocalyptic-Punkabuilder/src/main/resources/model/punkapocalyptic-model-unit-armor.xml
<?xml version="1.0" encoding="UTF-8"?>
<unit_armors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="validation/punkapocalyptic-model-unit-armor.xsd">
	<unit_armor>
		<unit>addler</unit>
		<armor>unarmored</armor>
	</unit_armor>
	<unit_armor>
		<unit>bobblehead</unit>
		<armor>unarmored</armor>
	</unit_armor>
	<unit_armor>
		<unit>chief</unit>
		<armor>hardened_leather</armor>
		<armors>
			<armor>
				<name>bulletproof_vest</name>
				<cost>10</cost>
			</armor>
			<armor>
				<name>metallic_armor</name>
				<cost>10</cost>
			</armor>
		</armors>
	</unit_armor>
	<unit_armor>
		<unit>badass</unit>
		<armor>thick_clothes</armor>
		<armors>
			<armor>
				<name>hardened_leather</name>
				<cost>5</cost>
			</armor>
			<armor>
				<name>metallic_armor</name>
				<cost>15</cost>
			</armor>
		</armors>
	</unit_armor>
	<unit_armor>
		<unit>brute</unit>
		<armor>hardened_leather</armor>
		<armors>
			<armor>
				<name>metallic_armor</name>
				<cost>10</cost>
			</armor>
			<armor>
				<name>metal_plate</name>
				<cost>15</cost>
			</armor>
		</armors>
	</unit_armor>
	<unit_armor>
		<unit>ganger</unit>
		<armor>thick_clothes</armor>
		<armors>
			<armor>
				<name>hardened_leather</name>
				<cost>5</cost>
			</armor>
		</armors>
	</unit_armor>
	<unit_armor>
		<unit>mongrelmorph</unit>
		<armor>unarmored</armor>
	</unit_armor>
	<unit_armor>
		<unit>mutard</unit>
		<armor>unarmored</armor>
	</unit_armor>
	<unit_armor>
		<unit>pit_beast</unit>
		<armor>unarmored</armor>
	</unit_armor>
	<unit_armor>
		<unit>scumbag</unit>
		<armor>thick_clothes</armor>
	</unit_armor>
</unit_armors>
