=== Bernardo-MG/Tabletop-Punkapocalyptic-Punkabuilder/src/main/resources/model/validation/punkapocalyptic-model-weapon-ranged.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="weapon_ranged_profiles">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="weapon_ranged_profile" type="weapon" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="weapon" />
			<xs:field xpath="name" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="weapon">
		<xs:sequence>
			<xs:element name="name" type="xs:token" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="firearm" type="xs:boolean" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="rules" type="rulesList" maxOccurs="1"
				minOccurs="0">
				<xs:unique name="uniqueRule">
					<xs:selector xpath="rule" />
					<xs:field xpath="." />
				</xs:unique>
			</xs:element>
			<xs:element name="penetration" type="ranges" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="strength" type="ranges" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="range" type="rangeInternational"
				maxOccurs="1" minOccurs="1" />
			<xs:element name="cost" type="xs:int" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="rangeInternational">
		<xs:sequence>
			<xs:element name="inches" type="ranges" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="cm" type="ranges" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="rulesList">
		<xs:sequence>
			<xs:element name="rule" type="xs:token" maxOccurs="unbounded"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ranges">
		<xs:sequence>
			<xs:element name="short" type="xs:int" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="medium" type="xs:int" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="long" type="xs:int" maxOccurs="1"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Punkapocalyptic-Punkabuilder/src/main/resources/model/punkapocalyptic-model-weapon-ranged.xml
<?xml version="1.0" encoding="UTF-8"?>
<weapon_ranged_profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="validation/punkapocalyptic-model-weapon-ranged.xsd">
	<weapon_ranged_profile>
		<name>automatic_rifle</name>
		<firearm>true</firearm>
		<rules>
			<rule>automatic</rule>
			<rule>firearm</rule>
			<rule>two-handed</rule>
		</rules>
		<penetration>
			<short>5</short>
			<medium>5</medium>
			<long>5</long>
		</penetration>
		<strength>
			<short>6</short>
			<medium>6</medium>
			<long>6</long>
		</strength>
		<range>
			<inches>
				<short>12</short>
				<medium>24</medium>
				<long>36</long>
			</inches>
			<cm>
				<short>30</short>
				<medium>60</medium>
				<long>90</long>
			</cm>
		</range>
		<cost>10</cost>
	</weapon_ranged_profile>
	<weapon_ranged_profile>
		<name>bow</name>
		<firearm>false</firearm>
		<rules>
			<rule>hard_to_use</rule>
			<rule>two-handed</rule>
		</rules>
		<penetration>
			<short>2</short>
			<medium>2</medium>
			<long>2</long>
		</penetration>
		<strength>
			<short>3</short>
			<medium>3</medium>
			<long>3</long>
		</strength>
		<range>
			<inches>
				<short>8</short>
				<medium>16</medium>
				<long>24</long>
			</inches>
			<cm>
				<short>20</short>
				<medium>40</medium>
				<long>60</long>
			</cm>
		</range>
		<cost>10</cost>
	</weapon_ranged_profile>
	<weapon_ranged_profile>
		<name>crossbow</name>
		<firearm>false</firearm>
		<rules>
			<rule>dead_slow</rule>
			<rule>two-handed</rule>
		</rules>
		<penetration>
			<short>3</short>
			<medium>3</medium>
			<long>3</long>
		</penetration>
		<strength>
			<short>4</short>
			<medium>4</medium>
			<long>4</long>
		</strength>
		<range>
			<inches>
				<short>6</short>
				<medium>12</medium>
				<long>18</long>
			</inches>
			<cm>
				<short>15</short>
				<medium>30</medium>
				<long>45</long>
			</cm>
		</range>
		<cost>8</cost>
	</weapon_ranged_profile>
	<weapon_ranged_profile>
		<name>pistol</name>
		<firearm>true</firearm>
		<rules>
			<rule>firearm</rule>
		</rules>
		<penetration>
			<short>4</short>
			<medium>4</medium>
			<long>4</long>
		</penetration>
		<strength>
			<short>6</short>
			<medium>6</medium>
			<long>6</long>
		</strength>
		<range>
			<inches>
				<short>6</short>
				<medium>12</medium>
				<long>18</long>
			</inches>
			<cm>
				<short>15</short>
				<medium>30</medium>
				<long>45</long>
			</cm>
		</range>
		<cost>5</cost>
	</weapon_ranged_profile>
	<weapon_ranged_profile>
		<name>rifle</name>
		<firearm>true</firearm>
		<rules>
			<rule>firearm</rule>
			<rule>two-handed</rule>
		</rules>
		<penetration>
			<short>5</short>
			<medium>5</medium>
			<long>5</long>
		</penetration>
		<strength>
			<short>6</short>
			<medium>6</medium>
			<long>6</long>
		</strength>
		<range>
			<inches>
				<short>12</short>
				<medium>24</medium>
				<long>36</long>
			</inches>
			<cm>
				<short>30</short>
				<medium>60</medium>
				<long>90</long>
			</cm>
		</range>
		<cost>8</cost>
	</weapon_ranged_profile>
	<weapon_ranged_profile>
		<name>shotgun</name>
		<firearm>true</firearm>
		<rules>
			<rule>firearm</rule>
			<rule>pellets</rule>
			<rule>two-handed</rule>
		</rules>
		<penetration>
			<short>3</short>
			<medium>3</medium>
			<long>3</long>
		</penetration>
		<strength>
			<short>7</short>
			<medium>6</medium>
			<long>5</long>
		</strength>
		<range>
			<inches>
				<short>4</short>
				<medium>8</medium>
				<long>12</long>
			</inches>
			<cm>
				<short>10</short>
				<medium>20</medium>
				<long>30</long>
			</cm>
		</range>
		<cost>6</cost>
	</weapon_ranged_profile>
	<weapon_ranged_profile>
		<name>throwing_knife</name>
		<firearm>false</firearm>
		<penetration>
			<short>2</short>
			<medium>1</medium>
			<long>0</long>
		</penetration>
		<strength>
			<short>0</short>
			<medium>-1</medium>
			<long>-2</long>
		</strength>
		<range>
			<inches>
				<short>2</short>
				<medium>4</medium>
				<long>6</long>
			</inches>
			<cm>
				<short>5</short>
				<medium>10</medium>
				<long>15</long>
			</cm>
		</range>
		<cost>3</cost>
	</weapon_ranged_profile>
</weapon_ranged_profiles>
