=== Bernardo-MG/Tabletop-Punkapocalyptic-Punkabuilder/src/main/resources/model/validation/punkapocalyptic-model-unit-rule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="unit_rules">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="unit_rule" type="unitRule" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="unit" />
			<xs:field xpath="." />
		</xs:unique>
	</xs:element>

	<xs:complexType name="unitRule">
		<xs:sequence>
			<xs:element name="unit" type="xs:token" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="rules" type="ruleList"
				maxOccurs="1" minOccurs="1">
				<xs:unique name="uniqueEquipment">
					<xs:selector xpath="equipment_piece" />
					<xs:field xpath="." />
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ruleList">
		<xs:sequence>
			<xs:element name="rule" type="xs:token"
				maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/Tabletop-Punkapocalyptic-Punkabuilder/src/main/resources/model/punkapocalyptic-model-unit-rule.xml
<?xml version="1.0" encoding="UTF-8"?>
<unit_rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="validation/punkapocalyptic-model-unit-rule.xsd">
	<unit_rule>
		<unit>addler</unit>
		<rules>
			<rule>pack</rule>
			<rule>mong</rule>
		</rules>
	</unit_rule>
	<unit_rule>
		<unit>mongrelmorph</unit>
		<rules>
			<rule>beast</rule>
			<rule>swift</rule>
		</rules>
	</unit_rule>
	<unit_rule>
		<unit>pit_beast</unit>
		<rules>
			<rule>berserk</rule>
		</rules>
	</unit_rule>
</unit_rules>
